name: amakano_compact_40_60_80
model_type: default
scale: 2
num_gpu: 1
use_amp: true
bfloat16: true
compile: false
manual_seed: 1337

datasets:
  train:
    type: paired
    dataroot_gt: R:\40_60_80\hr
    dataroot_lq: R:\40_60_80\lr
    io_backend:
      type: disk

    gt_size: 384
    batch_size: 20
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 8
    dataset_enlarge_ratio: 10

  val:
    name: val_1
    type: paired
    dataroot_gt: R:\amakano\val\hr
    dataroot_lq: R:\amakano\val\lr
    io_backend:
        type: disk
val:
  val_freq: 5000
  save_img: true
  metrics:
    psnr: 
      type: calculate_psnr
    ssim:
      type: calculate_ssim

path:
  pretrain_network_g: 'E:\project\neosr\experiments\amakano_compact_40-50-60-70-80\models\net_g_latest.pth'
  param_key_g: params
  strict_load_g: true
  resume_state: ~

network_g:
  type: compact
  num_feat: 24
  num_conv: 8

#print_network: true

train:
  optim_g:
    type: adan
    lr: !!float 8e-4
    weight_decay: 0.02
    weight_decouple: true
    use_gc: true
    adanorm: true
    # betas: [0.9, 0.99]

  scheduler:
    type: multisteplr
    milestones: [40000, 80000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0

logger:
  print_freq: 100
  save_checkpoint_freq: 2500
  use_tb_logger: true