name: otomedomain_a4k_per
model_type: default
scale: 2
num_gpu: 1
use_amp: true
bfloat16: true
compile: false
# manual_seed: 1024

datasets:
  train:
    type: paired
    dataroot_gt: R:\otome\Output\hr
    dataroot_lq: R:\otome\Output\lr
    io_backend:
      type: disk

    gt_size: 384
    batch_size: 10
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 8
    dataset_enlarge_ratio: 10

  val:
    name: val_1
    type: paired
    dataroot_gt: R:\otome\val\hr
    dataroot_lq: R:\otome\val\lr
    io_backend:
        type: disk
val:
  val_freq: 5000
  save_img: true
  metrics:
    psnr: 
      type: calculate_psnr
    ssim:
      type: calculate_ssim

path:
  pretrain_network_g: 'E:\project\neosr\experiments\otomedomain_a4k\models\net_g_latest.pth'
  param_key_g: params
  strict_load_g: true
  resume_state: ~

network_g:
  type: anime4k
  num_feat: 16

#print_network: true

train:
  optim_g:
    type: adan
    lr: !!float 2e-3
    weight_decay: 0.02
    weight_decouple: true
    use_gc: true
    adanorm: true
    # betas: [0.9, 0.99]

  scheduler:
    type: multisteplr
    milestones: [40000, 80000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 100.0
  # ldl_opt:
  #   type: L1Loss
  #   loss_weight: 1.0
  #   reduction: mean
  # ff_opt:
  #  type: focalfrequencyloss
  #  loss_weight: 1.0
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
        'conv1_2': 0.1
        'conv2_2': 0.1
        'conv3_4': 1
        'conv4_4': 1
        'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0
    criterion: l1

logger:
  print_freq: 100
  save_checkpoint_freq: 2500
  use_tb_logger: true